// Code generated by goctl. DO NOT EDIT.
package types

type FizzbuzzRequest struct {
	Count int32 `json:"count"`
}

type FizzbuzzResponse struct {
	Status  int32  `json:"status"`
	Message string `json:"message"`
}
